package Shop.Bar.domain.sm;

public enum OrderStatus {

    NEW, VALIDATED, VALIDATION_EXCEPTION, ALLOCATED, ALLOCATION_PENDING, ALLOCATION_EXCEPTION,
    VALIDATION_PENDING, PICKED_UP, DELIVERED, DELIVERY_EXCEPTION,CANCELLED, PENDING_INVENTORY
}
